site_name: Inception使用规范及说明文档
theme: readthedocs
pages: 
- 'Inception使用规范及说明文档': 'index.md'
- 'Inception序': 'chapter1.md'
- 'Inception是如何诞生的': 'source.md'
- 'Inception总述及体系结构': 'inception.md'
- 'Inception安装说明': 'install.md'
- 'Inception使用方法': 'usage.md'
- 'Inception支持选项及意义': 'option.md'
- 'Inception备份功能说明': 'backup.md'
- 'Inception审核规范及原则': 'rules.md'
- 'Inception所支持的参数变量': 'variables.md'
- 'Inception结果集': 'results.md'
- 'Inception命令集': 'command.md'
- 'Inception对线上配置需求': 'requires.md'
- 'Inception额外功能说明': 'extras.md'
- 'Inception对OSC的支持': 'osc.md'
- 'Inception执行进度控制': 'progress.md'
- 'Inception的统计功能': 'statistic.md'
- 'Inception语法树打印': 'queryprint.md'
- 'InceptionGate开发者手册': 'inception_gate_rd.md'
- 'InceptionGateDBA运维手册': 'inception_gate_dba.md'
- 'Inception发布日志': 'release.md'
