#define  ER_ERROR_FIRST                                                       1000
#define  ER_WARNING                                                           1001
#define  ER_NO                                                                1002
#define  ER_YES                                                               1003
#define  ER_CANT_CREATE_FILE                                                  1004
#define  ER_CANT_CREATE_TABLE                                                 1005
#define  ER_CANT_CREATE_DB                                                    1006
#define  ER_DB_CREATE_EXISTS                                                  1007
#define  ER_DB_DROP_EXISTS                                                    1008
#define  ER_DB_DROP_DELETE                                                    1009
#define  ER_DB_DROP_RMDIR                                                     1010
#define  ER_CANT_DELETE_FILE                                                  1011
#define  ER_CANT_FIND_SYSTEM_REC                                              1012
#define  ER_CANT_GET_STAT                                                     1013
#define  ER_CANT_GET_WD                                                       1014
#define  ER_CANT_LOCK                                                         1015
#define  ER_CANT_OPEN_FILE                                                    1016
#define  ER_FILE_NOT_FOUND                                                    1017
#define  ER_CANT_READ_DIR                                                     1018
#define  ER_CANT_SET_WD                                                       1019
#define  ER_CHECKREAD                                                         1020
#define  ER_DISK_FULL                                                         1021
#define  ER_DUP_KEY                                                           1022
#define  ER_ERROR_ON_CLOSE                                                    1023
#define  ER_ERROR_ON_READ                                                     1024
#define  ER_ERROR_ON_RENAME                                                   1025
#define  ER_ERROR_ON_WRITE                                                    1026
#define  ER_FILE_USED                                                         1027
#define  ER_FILSORT_ABORT                                                     1028
#define  ER_FORM_NOT_FOUND                                                    1029
#define  ER_GET_ERRNO                                                         1030
#define  ER_ILLEGAL_HA                                                        1031
#define  ER_KEY_NOT_FOUND                                                     1032
#define  ER_NOT_FORM_FILE                                                     1033
#define  ER_NOT_KEYFILE                                                       1034
#define  ER_OLD_KEYFILE                                                       1035
#define  ER_OPEN_AS_READONLY                                                  1036
#define  ER_OUT_OF_SORTMEMORY                                                 1037
#define  ER_UNEXPECTED_EOF                                                    1038
#define  ER_OUT_OF_RESOURCES                                                  1039
#define  ER_BAD_HOST_ERROR                                                    1040
#define  ER_HANDSHAKE_ERROR                                                   1041
#define  ER_DBACCESS_DENIED_ERROR                                             1042
#define  ER_ACCESS_DENIED_ERROR                                               1043
#define  ER_UNKNOWN_COM_ERROR                                                 1044
#define  ER_BAD_DB_ERROR                                                      1045
#define  ER_BAD_TABLE_ERROR                                                   1046
#define  ER_SERVER_SHUTDOWN                                                   1047
#define  ER_WRONG_FIELD_WITH_GROUP                                            1048
#define  ER_WRONG_GROUP_FIELD                                                 1049
#define  ER_WRONG_SUM_SELECT                                                  1050
#define  ER_WRONG_VALUE_COUNT                                                 1051
#define  ER_DUP_ENTRY                                                         1052
#define  ER_WRONG_FIELD_SPEC                                                  1053
#define  ER_EMPTY_QUERY                                                       1054
#define  ER_NONUNIQ_TABLE                                                     1055
#define  ER_TOO_BIG_FIELDLENGTH                                               1056
#define  ER_READY                                                             1057
#define  ER_GOT_SIGNAL                                                        1058
#define  ER_IPSOCK_ERROR                                                      1059
#define  ER_NO_SUCH_INDEX                                                     1060
#define  ER_WRONG_FIELD_TERMINATORS                                           1061
#define  ER_BLOBS_AND_NO_TERMINATED                                           1062
#define  ER_TEXTFILE_NOT_READABLE                                             1063
#define  ER_FILE_EXISTS_ERROR                                                 1064
#define  ER_LOAD_INFO                                                         1065
#define  ER_ALTER_INFO                                                        1066
#define  ER_CANT_REMOVE_ALL_FIELDS                                            1067
#define  ER_INSERT_INFO                                                       1068
#define  ER_UPDATE_TABLE_USED                                                 1069
#define  ER_NO_SUCH_THREAD                                                    1070
#define  ER_KILL_DENIED_ERROR                                                 1071
#define  ER_NO_TABLES_USED                                                    1072
#define  ER_TOO_BIG_SET                                                       1073
#define  ER_NO_UNIQUE_LOGFILE                                                 1074
#define  ER_TABLE_NOT_LOCKED_FOR_WRITE                                        1075
#define  ER_TABLE_NOT_LOCKED                                                  1076
#define  ER_WRONG_TABLE_NAME                                                  1077
#define  ER_TOO_BIG_SELECT                                                    1078
#define  ER_UNKNOWN_ERROR                                                     1079
#define  ER_UNKNOWN_PROCEDURE                                                 1080
#define  ER_WRONG_PARAMCOUNT_TO_PROCEDURE                                     1081
#define  ER_WRONG_PARAMETERS_TO_PROCEDURE                                     1082
#define  ER_UNSUPPORTED_EXTENSION                                             1083
#define  ER_TABLE_MUST_HAVE_COLUMNS                                           1084
#define  ER_RECORD_FILE_FULL                                                  1085
#define  ER_TOO_MANY_TABLES                                                   1086
#define  ER_TOO_MANY_FIELDS                                                   1087
#define  ER_TOO_BIG_ROWSIZE                                                   1088
#define  ER_STACK_OVERRUN                                                     1089
#define  ER_WRONG_OUTER_JOIN                                                  1090
#define  ER_NULL_COLUMN_IN_INDEX                                              1091
#define  ER_CANT_FIND_UDF                                                     1092
#define  ER_CANT_INITIALIZE_UDF                                               1093
#define  ER_UDF_NO_PATHS                                                      1094
#define  ER_UDF_EXISTS                                                        1095
#define  ER_CANT_OPEN_LIBRARY                                                 1096
#define  ER_CANT_FIND_DL_ENTRY                                                1097
#define  ER_FUNCTION_NOT_DEFINED                                              1098
#define  ER_HOST_IS_BLOCKED                                                   1099
#define  ER_HOST_NOT_PRIVILEGED                                               1100
#define  ER_PASSWORD_ANONYMOUS_USER                                           1101
#define  ER_PASSWORD_NOT_ALLOWED                                              1102
#define  ER_PASSWORD_NO_MATCH                                                 1103
#define  ER_UPDATE_INFO                                                       1104
#define  ER_CANT_CREATE_THREAD                                                1105
#define  ER_CANT_REOPEN_TABLE                                                 1106
#define  ER_INVALID_USE_OF_NULL                                               1107
#define  ER_REGEXP_ERROR                                                      1108
#define  ER_MIX_OF_GROUP_FUNC_AND_FIELDS                                      1109
#define  ER_NONEXISTING_GRANT                                                 1110
#define  ER_TABLEACCESS_DENIED_ERROR                                          1111
#define  ER_COLUMNACCESS_DENIED_ERROR                                         1112
#define  ER_ILLEGAL_GRANT_FOR_TABLE                                           1113
#define  ER_GRANT_WRONG_HOST_OR_USER                                          1114
#define  ER_NO_SUCH_TABLE                                                     1115
#define  ER_NONEXISTING_TABLE_GRANT                                           1116
#define  ER_NOT_ALLOWED_COMMAND                                               1117
#define  ER_DELAYED_CANT_CHANGE_LOCK                                          1118
#define  ER_TOO_MANY_DELAYED_THREADS                                          1119
#define  ER_ABORTING_CONNECTION                                               1120
#define  ER_NET_PACKET_TOO_LARGE                                              1121
#define  ER_NET_READ_ERROR_FROM_PIPE                                          1122
#define  ER_NET_FCNTL_ERROR                                                   1123
#define  ER_NET_UNCOMPRESS_ERROR                                              1124
#define  ER_NET_WRITE_INTERRUPTED                                             1125
#define  ER_TOO_LONG_STRING                                                   1126
#define  ER_TABLE_CANT_HANDLE_BLOB                                            1127
#define  ER_DELAYED_INSERT_TABLE_LOCKED                                       1128
#define  ER_WRONG_MRG_TABLE                                                   1129
#define  ER_DUP_UNIQUE                                                        1130
#define  ER_BLOB_KEY_WITHOUT_LENGTH                                           1131
#define  ER_PRIMARY_CANT_HAVE_NULL                                            1132
#define  ER_TOO_MANY_ROWS                                                     1133
#define  ER_REQUIRES_PRIMARY_KEY                                              1134
#define  ER_NO_RAID_COMPILED                                                  1135
#define  ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE                                   1136
#define  ER_KEY_DOES_NOT_EXITS                                                1137
#define  ER_CHECK_NO_SUCH_TABLE                                               1138
#define  ER_CHECK_NOT_IMPLEMENTED                                             1139
#define  ER_CANT_DO_THIS_DURING_AN_TRANSACTION                                1140
#define  ER_ERROR_DURING_COMMIT                                               1141
#define  ER_ERROR_DURING_ROLLBACK                                             1142
#define  ER_ERROR_DURING_FLUSH_LOGS                                           1143
#define  ER_ERROR_DURING_CHECKPOINT                                           1144
#define  ER_NEW_ABORTING_CONNECTION                                           1145
#define  ER_DUMP_NOT_IMPLEMENTED                                              1146
#define  ER_FLUSH_MASTER_BINLOG_CLOSED                                        1147
#define  ER_INDEX_REBUILD                                                     1148
#define  ER_MASTER                                                            1149
#define  ER_MASTER_NET_READ                                                   1150
#define  ER_MASTER_NET_WRITE                                                  1151
#define  ER_FT_MATCHING_KEY_NOT_FOUND                                         1152
#define  ER_LOCK_OR_ACTIVE_TRANSACTION                                        1153
#define  ER_CRASHED_ON_USAGE                                                  1154
#define  ER_CRASHED_ON_REPAIR                                                 1155
#define  ER_WARNING_NOT_COMPLETE_ROLLBACK                                     1156
#define  ER_TRANS_CACHE_FULL                                                  1157
#define  ER_SLAVE_MUST_STOP                                                   1158
#define  ER_SLAVE_NOT_RUNNING                                                 1159
#define  ER_BAD_SLAVE                                                         1160
#define  ER_MASTER_INFO                                                       1161
#define  ER_SLAVE_THREAD                                                      1162
#define  ER_TOO_MANY_USER_CONNECTIONS                                         1163
#define  ER_SET_CONSTANTS_ONLY                                                1164
#define  ER_LOCK_WAIT_TIMEOUT                                                 1165
#define  ER_LOCK_TABLE_FULL                                                   1166
#define  ER_READ_ONLY_TRANSACTION                                             1167
#define  ER_DROP_DB_WITH_READ_LOCK                                            1168
#define  ER_CREATE_DB_WITH_READ_LOCK                                          1169
#define  ER_NO_PERMISSION_TO_CREATE_USER                                      1170
#define  ER_UNION_TABLES_IN_DIFFERENT_DIR                                     1171
#define  ER_LOCK_DEADLOCK                                                     1172
#define  ER_TABLE_CANT_HANDLE_FT                                              1173
#define  ER_CANNOT_ADD_FOREIGN                                                1174
#define  ER_NO_REFERENCED_ROW                                                 1175
#define  ER_ROW_IS_REFERENCED                                                 1176
#define  ER_CONNECT_TO_MASTER                                                 1177
#define  ER_QUERY_ON_MASTER                                                   1178
#define  ER_ERROR_WHEN_EXECUTING_COMMAND                                      1179
#define  ER_WRONG_USAGE                                                       1180
#define  ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT                                 1181
#define  ER_CANT_UPDATE_WITH_READLOCK                                         1182
#define  ER_MIXING_NOT_ALLOWED                                                1183
#define  ER_DUP_ARGUMENT                                                      1184
#define  ER_USER_LIMIT_REACHED                                                1185
#define  ER_SPECIFIC_ACCESS_DENIED_ERROR                                      1186
#define  ER_LOCAL_VARIABLE                                                    1187
#define  ER_GLOBAL_VARIABLE                                                   1188
#define  ER_NO_DEFAULT                                                        1189
#define  ER_WRONG_TYPE_FOR_VAR                                                1190
#define  ER_VAR_CANT_BE_READ                                                  1191
#define  ER_CANT_USE_OPTION_HERE                                              1192
#define  ER_MASTER_FATAL_ERROR_READING_BINLOG                                 1193
#define  ER_SLAVE_IGNORED_TABLE                                               1194
#define  ER_WRONG_FK_DEF                                                      1195
#define  ER_KEY_REF_DO_NOT_MATCH_TABLE_REF                                    1196
#define  ER_OPERAND_COLUMNS                                                   1197
#define  ER_SUBQUERY_NO_1_ROW                                                 1198
#define  ER_UNKNOWN_STMT_HANDLER                                              1199
#define  ER_CORRUPT_HELP_DB                                                   1200
#define  ER_CYCLIC_REFERENCE                                                  1201
#define  ER_AUTO_CONVERT                                                      1202
#define  ER_ILLEGAL_REFERENCE                                                 1203
#define  ER_SELECT_REDUCED                                                    1204
#define  ER_TABLENAME_NOT_ALLOWED_HERE                                        1205
#define  ER_NOT_SUPPORTED_AUTH_MODE                                           1206
#define  ER_SPATIAL_CANT_HAVE_NULL                                            1207
#define  ER_SLAVE_WAS_RUNNING                                                 1208
#define  ER_SLAVE_WAS_NOT_RUNNING                                             1209
#define  ER_TOO_BIG_FOR_UNCOMPRESS                                            1210
#define  ER_ZLIB_Z_MEM_ERROR                                                  1211
#define  ER_ZLIB_Z_BUF_ERROR                                                  1212
#define  ER_ZLIB_Z_DATA_ERROR                                                 1213
#define  ER_CUT_VALUE_GROUP_CONCAT                                            1214
#define  ER_WARN_TOO_FEW_RECORDS                                              1215
#define  ER_WARN_TOO_MANY_RECORDS                                             1216
#define  ER_WARN_NULL_TO_NOTNULL                                              1217
#define  ER_WARN_DATA_OUT_OF_RANGE                                            1218
#define  WARN_DATA_TRUNCATED                                                  1219
#define  ER_WARN_USING_OTHER_HANDLER                                          1220
#define  ER_CANT_AGGREGATE_2COLLATIONS                                        1221
#define  ER_DROP_USER                                                         1222
#define  ER_REVOKE_GRANTS                                                     1223
#define  ER_CANT_AGGREGATE_3COLLATIONS                                        1224
#define  ER_CANT_AGGREGATE_NCOLLATIONS                                        1225
#define  ER_VARIABLE_IS_NOT_STRUCT                                            1226
#define  ER_SLAVE_IGNORED_SSL_PARAMS                                          1227
#define  ER_SERVER_IS_IN_SECURE_AUTH_MODE                                     1228
#define  ER_WARN_FIELD_RESOLVED                                               1229
#define  ER_BAD_SLAVE_UNTIL_COND                                              1230
#define  ER_MISSING_SKIP_SLAVE                                                1231
#define  ER_UNTIL_COND_IGNORED                                                1232
#define  ER_WRONG_NAME_FOR_CATALOG                                            1233
#define  ER_WARN_QC_RESIZE                                                    1234
#define  ER_BAD_FT_COLUMN                                                     1235
#define  ER_UNKNOWN_KEY_CACHE                                                 1236
#define  ER_WARN_HOSTNAME_WONT_WORK                                           1237
#define  ER_UNKNOWN_STORAGE_ENGINE                                            1238
#define  ER_WARN_DEPRECATED_SYNTAX                                            1239
#define  ER_NON_UPDATABLE_TABLE                                               1240
#define  ER_FEATURE_DISABLED                                                  1241
#define  ER_OPTION_PREVENTS_STATEMENT                                         1242
#define  ER_DUPLICATED_VALUE_IN_TYPE                                          1243
#define  ER_UNSUPPORTED_PS                                                    1244
#define  ER_GET_ERRMSG                                                        1245
#define  ER_GET_TEMPORARY_ERRMSG                                              1246
#define  ER_UNKNOWN_TIME_ZONE                                                 1247
#define  ER_WARN_INVALID_TIMESTAMP                                            1248
#define  ER_INVALID_CHARACTER_STRING                                          1249
#define  ER_WARN_ALLOWED_PACKET_OVERFLOWED                                    1250
#define  ER_SP_NO_RECURSIVE_CREATE                                            1251
#define  ER_SP_ALREADY_EXISTS                                                 1252
#define  ER_SP_DOES_NOT_EXIST                                                 1253
#define  ER_SP_DROP_FAILED                                                    1254
#define  ER_SP_STORE_FAILED                                                   1255
#define  ER_SP_LILABEL_MISMATCH                                               1256
#define  ER_SP_LABEL_REDEFINE                                                 1257
#define  ER_SP_LABEL_MISMATCH                                                 1258
#define  ER_SP_UNINIT_VAR                                                     1259
#define  ER_SP_BADSELECT                                                      1260
#define  ER_SP_BADRETURN                                                      1261
#define  ER_SP_BADSTATEMENT                                                   1262
#define  ER_UPDATE_LOG_DEPRECATED_IGNORED                                     1263
#define  ER_UPDATE_LOG_DEPRECATED_TRANSLATED                                  1264
#define  ER_QUERY_INTERRUPTED                                                 1265
#define  ER_SP_WRONG_NO_OF_ARGS                                               1266
#define  ER_SP_COND_MISMATCH                                                  1267
#define  ER_SP_NORETURN                                                       1268
#define  ER_SP_NORETURNEND                                                    1269
#define  ER_SP_BAD_CURSOR_QUERY                                               1270
#define  ER_SP_BAD_CURSOR_SELECT                                              1271
#define  ER_SP_CURSOR_MISMATCH                                                1272
#define  ER_SP_CURSOR_ALREADY_OPEN                                            1273
#define  ER_SP_CURSOR_NOT_OPEN                                                1274
#define  ER_SP_UNDECLARED_VAR                                                 1275
#define  ER_SP_WRONG_NO_OF_FETCH_ARGS                                         1276
#define  ER_SP_FETCH_NO_DATA                                                  1277
#define  ER_SP_DUP_PARAM                                                      1278
#define  ER_SP_DUP_VAR                                                        1279
#define  ER_SP_DUP_COND                                                       1280
#define  ER_SP_DUP_CURS                                                       1281
#define  ER_SP_CANT_ALTER                                                     1282
#define  ER_SP_SUBSELECT_NYI                                                  1283
#define  ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG                                     1284
#define  ER_SP_VARCOND_AFTER_CURSHNDLR                                        1285
#define  ER_SP_CURSOR_AFTER_HANDLER                                           1286
#define  ER_SP_CASE_NOT_FOUND                                                 1287
#define  ER_FPARSER_TOO_BIG_FILE                                              1288
#define  ER_FPARSER_BAD_HEADER                                                1289
#define  ER_FPARSER_EOF_IN_COMMENT                                            1290
#define  ER_FPARSER_ERROR_IN_PARAMETER                                        1291
#define  ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER                                  1292
#define  ER_VIEW_NO_EXPLAIN                                                   1293
#define  ER_FRM_UNKNOWN_TYPE                                                  1294
#define  ER_WRONG_OBJECT                                                      1295
#define  ER_NONUPDATEABLE_COLUMN                                              1296
#define  ER_VIEW_SELECT_DERIVED                                               1297
#define  ER_VIEW_SELECT_VARIABLE                                              1298
#define  ER_VIEW_SELECT_TMPTABLE                                              1299
#define  ER_VIEW_WRONG_LIST                                                   1300
#define  ER_WARN_VIEW_MERGE                                                   1301
#define  ER_WARN_VIEW_WITHOUT_KEY                                             1302
#define  ER_VIEW_INVALID                                                      1303
#define  ER_SP_NO_DROP_SP                                                     1304
#define  ER_SP_GOTO_IN_HNDLR                                                  1305
#define  ER_TRG_ALREADY_EXISTS                                                1306
#define  ER_TRG_DOES_NOT_EXIST                                                1307
#define  ER_TRG_ON_VIEW_OR_TEMP_TABLE                                         1308
#define  ER_TRG_CANT_CHANGE_ROW                                               1309
#define  ER_TRG_NO_SUCH_ROW_IN_TRG                                            1310
#define  ER_NO_DEFAULT_FOR_FIELD                                              1311
#define  ER_DIVISION_BY_ZERO                                                  1312
#define  ER_TRUNCATED_WRONG_VALUE_FOR_FIELD                                   1313
#define  ER_ILLEGAL_VALUE_FOR_TYPE                                            1314
#define  ER_VIEW_NONUPD_CHECK                                                 1315
#define  ER_VIEW_CHECK_FAILED                                                 1316
#define  ER_PROCACCESS_DENIED_ERROR                                           1317
#define  ER_RELAY_LOG_FAIL                                                    1318
#define  ER_PASSWD_LENGTH                                                     1319
#define  ER_UNKNOWN_TARGET_BINLOG                                             1320
#define  ER_IO_ERR_LOG_INDEX_READ                                             1321
#define  ER_BINLOG_PURGE_PROHIBITED                                           1322
#define  ER_FSEEK_FAIL                                                        1323
#define  ER_BINLOG_PURGE_FATAL_ERR                                            1324
#define  ER_LOG_IN_USE                                                        1325
#define  ER_LOG_PURGE_UNKNOWN_ERR                                             1326
#define  ER_RELAY_LOG_INIT                                                    1327
#define  ER_NO_BINARY_LOGGING                                                 1328
#define  ER_RESERVED_SYNTAX                                                   1329
#define  ER_WSAS_FAILED                                                       1330
#define  ER_DIFF_GROUPS_PROC                                                  1331
#define  ER_NO_GROUP_FOR_PROC                                                 1332
#define  ER_ORDER_WITH_PROC                                                   1333
#define  ER_LOGGING_PROHIBIT_CHANGING_OF                                      1334
#define  ER_NO_FILE_MAPPING                                                   1335
#define  ER_WRONG_MAGIC                                                       1336
#define  ER_PS_MANY_PARAM                                                     1337
#define  ER_KEY_PART_0                                                        1338
#define  ER_VIEW_CHECKSUM                                                     1339
#define  ER_VIEW_MULTIUPDATE                                                  1340
#define  ER_VIEW_NO_INSERT_FIELD_LIST                                         1341
#define  ER_VIEW_DELETE_MERGE_VIEW                                            1342
#define  ER_CANNOT_USER                                                       1343
#define  ER_XAER_NOTA                                                         1344
#define  ER_XAER_INVAL                                                        1345
#define  ER_XAER_RMFAIL                                                       1346
#define  ER_XAER_OUTSIDE                                                      1347
#define  ER_XAER_RMERR                                                        1348
#define  ER_XA_RBROLLBACK                                                     1349
#define  ER_NONEXISTING_PROC_GRANT                                            1350
#define  ER_PROC_AUTO_GRANT_FAIL                                              1351
#define  ER_PROC_AUTO_REVOKE_FAIL                                             1352
#define  ER_DATA_TOO_LONG                                                     1353
#define  ER_SP_BAD_SQLSTATE                                                   1354
#define  ER_STARTUP                                                           1355
#define  ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR                                  1356
#define  ER_CANT_CREATE_USER_WITH_GRANT                                       1357
#define  ER_WRONG_VALUE_FOR_TYPE                                              1358
#define  ER_TABLE_DEF_CHANGED                                                 1359
#define  ER_SP_DUP_HANDLER                                                    1360
#define  ER_SP_NOT_VAR_ARG                                                    1361
#define  ER_SP_NO_RETSET                                                      1362
#define  ER_CANT_CREATE_GEOMETRY_OBJECT                                       1363
#define  ER_FAILED_ROUTINE_BREAK_BINLOG                                       1364
#define  ER_BINLOG_UNSAFE_ROUTINE                                             1365
#define  ER_BINLOG_CREATE_ROUTINE_NEED_SUPER                                  1366
#define  ER_EXEC_STMT_WITH_OPEN_CURSOR                                        1367
#define  ER_STMT_HAS_NO_OPEN_CURSOR                                           1368
#define  ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG                                   1369
#define  ER_NO_DEFAULT_FOR_VIEW_FIELD                                         1370
#define  ER_SP_NO_RECURSION                                                   1371
#define  ER_TOO_BIG_SCALE                                                     1372
#define  ER_TOO_BIG_PRECISION                                                 1373
#define  ER_M_BIGGER_THAN_D                                                   1374
#define  ER_WRONG_LOCK_OF_SYSTEM_TABLE                                        1375
#define  ER_CONNECT_TO_FOREIGN_DATA_SOURCE                                    1376
#define  ER_QUERY_ON_FOREIGN_DATA_SOURCE                                      1377
#define  ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST                                  1378
#define  ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE                           1379
#define  ER_FOREIGN_DATA_STRING_INVALID                                       1380
#define  ER_CANT_CREATE_FEDERATED_TABLE                                       1381
#define  ER_TRG_IN_WRONG_SCHEMA                                               1382
#define  ER_STACK_OVERRUN_NEED_MORE                                           1383
#define  ER_TOO_LONG_BODY                                                     1384
#define  ER_WARN_CANT_DROP_DEFAULT_KEYCACHE                                   1385
#define  ER_TOO_BIG_DISPLAYWIDTH                                              1386
#define  ER_XAER_DUPID                                                        1387
#define  ER_DATETIME_FUNCTION_OVERFLOW                                        1388
#define  ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG                               1389
#define  ER_VIEW_PREVENT_UPDATE                                               1390
#define  ER_PS_NO_RECURSION                                                   1391
#define  ER_SP_CANT_SET_AUTOCOMMIT                                            1392
#define  ER_MALFORMED_DEFINER                                                 1393
#define  ER_VIEW_FRM_NO_USER                                                  1394
#define  ER_VIEW_OTHER_USER                                                   1395
#define  ER_NO_SUCH_USER                                                      1396
#define  ER_FORBID_SCHEMA_CHANGE                                              1397
#define  ER_ROW_IS_REFERENCED_2                                               1398
#define  ER_NO_REFERENCED_ROW_2                                               1399
#define  ER_SP_BAD_VAR_SHADOW                                                 1400
#define  ER_TRG_NO_DEFINER                                                    1401
#define  ER_OLD_FILE_FORMAT                                                   1402
#define  ER_SP_RECURSION_LIMIT                                                1403
#define  ER_SP_PROC_TABLE_CORRUPT                                             1404
#define  ER_SP_WRONG_NAME                                                     1405
#define  ER_TABLE_NEEDS_UPGRADE                                               1406
#define  ER_SP_NO_AGGREGATE                                                   1407
#define  ER_MAX_PREPARED_STMT_COUNT_REACHED                                   1408
#define  ER_VIEW_RECURSIVE                                                    1409
#define  ER_NON_GROUPING_FIELD_USED                                           1410
#define  ER_TABLE_CANT_HANDLE_SPKEYS                                          1411
#define  ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA                                      1412
#define  ER_AUTOINC_READ_FAILED                                               1413
#define  ER_NON_INSERTABLE_TABLE                                              1414
#define  ER_ADMIN_WRONG_MRG_TABLE                                             1415
#define  ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT                              1416
#define  ER_NAME_BECOMES_EMPTY                                                1417
#define  ER_AMBIGUOUS_FIELD_TERM                                              1418
#define  ER_FOREIGN_SERVER_EXISTS                                             1419
#define  ER_FOREIGN_SERVER_DOESNT_EXIST                                       1420
#define  ER_ILLEGAL_HA_CREATE_OPTION                                          1421
#define  ER_PARTITION_REQUIRES_VALUES_ERROR                                   1422
#define  ER_PARTITION_WRONG_VALUES_ERROR                                      1423
#define  ER_PARTITION_MAXVALUE_ERROR                                          1424
#define  ER_PARTITION_SUBPARTITION_ERROR                                      1425
#define  ER_PARTITION_SUBPART_MIX_ERROR                                       1426
#define  ER_PARTITION_WRONG_NO_PART_ERROR                                     1427
#define  ER_PARTITION_WRONG_NO_SUBPART_ERROR                                  1428
#define  ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR                                1429
#define  ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR                              1430
#define  ER_FIELD_NOT_FOUND_PART_ERROR                                        1431
#define  ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR                                 1432
#define  ER_INCONSISTENT_PARTITION_INFO_ERROR                                 1433
#define  ER_PARTITION_FUNC_NOT_ALLOWED_ERROR                                  1434
#define  ER_PARTITIONS_MUST_BE_DEFINED_ERROR                                  1435
#define  ER_RANGE_NOT_INCREASING_ERROR                                        1436
#define  ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR                              1437
#define  ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR                             1438
#define  ER_PARTITION_ENTRY_ERROR                                             1439
#define  ER_MIX_HANDLER_ERROR                                                 1440
#define  ER_PARTITION_NOT_DEFINED_ERROR                                       1441
#define  ER_TOO_MANY_PARTITIONS_ERROR                                         1442
#define  ER_SUBPARTITION_ERROR                                                1443
#define  ER_CANT_CREATE_HANDLER_FILE                                          1444
#define  ER_BLOB_FIELD_IN_PART_FUNC_ERROR                                     1445
#define  ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF                                  1446
#define  ER_NO_PARTS_ERROR                                                    1447
#define  ER_PARTITION_MGMT_ON_NONPARTITIONED                                  1448
#define  ER_FOREIGN_KEY_ON_PARTITIONED                                        1449
#define  ER_DROP_PARTITION_NON_EXISTENT                                       1450
#define  ER_DROP_LAST_PARTITION                                               1451
#define  ER_COALESCE_ONLY_ON_HASH_PARTITION                                   1452
#define  ER_REORG_HASH_ONLY_ON_SAME_NO                                        1453
#define  ER_REORG_NO_PARAM_ERROR                                              1454
#define  ER_ONLY_ON_RANGE_LIST_PARTITION                                      1455
#define  ER_ADD_PARTITION_SUBPART_ERROR                                       1456
#define  ER_ADD_PARTITION_NO_NEW_PARTITION                                    1457
#define  ER_COALESCE_PARTITION_NO_PARTITION                                   1458
#define  ER_REORG_PARTITION_NOT_EXIST                                         1459
#define  ER_SAME_NAME_PARTITION                                               1460
#define  ER_NO_BINLOG_ERROR                                                   1461
#define  ER_CONSECUTIVE_REORG_PARTITIONS                                      1462
#define  ER_REORG_OUTSIDE_RANGE                                               1463
#define  ER_PARTITION_FUNCTION_FAILURE                                        1464
#define  ER_PART_STATE_ERROR                                                  1465
#define  ER_LIMITED_PART_RANGE                                                1466
#define  ER_PLUGIN_IS_NOT_LOADED                                              1467
#define  ER_WRONG_VALUE                                                       1468
#define  ER_NO_PARTITION_FOR_GIVEN_VALUE                                      1469
#define  ER_FILEGROUP_OPTION_ONLY_ONCE                                        1470
#define  ER_CREATE_FILEGROUP_FAILED                                           1471
#define  ER_DROP_FILEGROUP_FAILED                                             1472
#define  ER_TABLESPACE_AUTO_EXTEND_ERROR                                      1473
#define  ER_WRONG_SIZE_NUMBER                                                 1474
#define  ER_SIZE_OVERFLOW_ERROR                                               1475
#define  ER_ALTER_FILEGROUP_FAILED                                            1476
#define  ER_BINLOG_ROW_LOGGING_FAILED                                         1477
#define  ER_BINLOG_ROW_WRONG_TABLE_DEF                                        1478
#define  ER_BINLOG_ROW_RBR_TO_SBR                                             1479
#define  ER_EVENT_ALREADY_EXISTS                                              1480
#define  ER_EVENT_STORE_FAILED                                                1481
#define  ER_EVENT_DOES_NOT_EXIST                                              1482
#define  ER_EVENT_CANT_ALTER                                                  1483
#define  ER_EVENT_DROP_FAILED                                                 1484
#define  ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG                            1485
#define  ER_EVENT_ENDS_BEFORE_STARTS                                          1486
#define  ER_EVENT_EXEC_TIME_IN_THE_PAST                                       1487
#define  ER_EVENT_OPEN_TABLE_FAILED                                           1488
#define  ER_EVENT_NEITHER_M_EXPR_NOR_M_AT                                     1489
#define  ER_OBSOLETE_COL_COUNT_DOESNT_MATCH_CORRUPTED                         1490
#define  ER_OBSOLETE_CANNOT_LOAD_FROM_TABLE                                   1491
#define  ER_EVENT_CANNOT_DELETE                                               1492
#define  ER_EVENT_COMPILE_ERROR                                               1493
#define  ER_EVENT_SAME_NAME                                                   1494
#define  ER_EVENT_DATA_TOO_LONG                                               1495
#define  ER_DROP_INDEX_FK                                                     1496
#define  ER_WARN_DEPRECATED_SYNTAX_WITH_VER                                   1497
#define  ER_CANT_WRITE_LOCK_LOG_TABLE                                         1498
#define  ER_CANT_LOCK_LOG_TABLE                                               1499
#define  ER_FOREIGN_DUPLICATE_KEY_OLD_UNUSED                                  1500
#define  ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE                              1501
#define  ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR                             1502
#define  ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT                     1503
#define  ER_NDB_CANT_SWITCH_BINLOG_FORMAT                                     1504
#define  ER_PARTITION_NO_TEMPORARY                                            1505
#define  ER_PARTITION_CONST_DOMAIN_ERROR                                      1506
#define  ER_PARTITION_FUNCTION_IS_NOT_ALLOWED                                 1507
#define  ER_DDL_LOG_ERROR                                                     1508
#define  ER_NULL_IN_VALUES_LESS_THAN                                          1509
#define  ER_WRONG_PARTITION_NAME                                              1510
#define  ER_CANT_CHANGE_TX_CHARACTERISTICS                                    1511
#define  ER_DUP_ENTRY_AUTOINCREMENT_CASE                                      1512
#define  ER_EVENT_MODIFY_QUEUE_ERROR                                          1513
#define  ER_EVENT_SET_VAR_ERROR                                               1514
#define  ER_PARTITION_MERGE_ERROR                                             1515
#define  ER_CANT_ACTIVATE_LOG                                                 1516
#define  ER_RBR_NOT_AVAILABLE                                                 1517
#define  ER_BASE64_DECODE_ERROR                                               1518
#define  ER_EVENT_RECURSION_FORBIDDEN                                         1519
#define  ER_EVENTS_DB_ERROR                                                   1520
#define  ER_ONLY_INTEGERS_ALLOWED                                             1521
#define  ER_UNSUPORTED_LOG_ENGINE                                             1522
#define  ER_BAD_LOG_STATEMENT                                                 1523
#define  ER_CANT_RENAME_LOG_TABLE                                             1524
#define  ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT                                    1525
#define  ER_WRONG_PARAMETERS_TO_NATIVE_FCT                                    1526
#define  ER_WRONG_PARAMETERS_TO_STORED_FCT                                    1527
#define  ER_NATIVE_FCT_NAME_COLLISION                                         1528
#define  ER_DUP_ENTRY_WITH_KEY_NAME                                           1529
#define  ER_BINLOG_PURGE_EMFILE                                               1530
#define  ER_EVENT_CANNOT_CREATE_IN_THE_PAST                                   1531
#define  ER_EVENT_CANNOT_ALTER_IN_THE_PAST                                    1532
#define  ER_SLAVE_INCIDENT                                                    1533
#define  ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT                               1534
#define  ER_BINLOG_UNSAFE_STATEMENT                                           1535
#define  ER_SLAVE_FATAL_ERROR                                                 1536
#define  ER_SLAVE_RELAY_LOG_READ_FAILURE                                      1537
#define  ER_SLAVE_CREATE_EVENT_FAILURE                                        1538
#define  ER_SLAVE_MASTER_COM_FAILURE                                          1539
#define  ER_BINLOG_LOGGING_IMPOSSIBLE                                         1540
#define  ER_VIEW_NO_CREATION_CTX                                              1541
#define  ER_VIEW_INVALID_CREATION_CTX                                         1542
#define  ER_SR_INVALID_CREATION_CTX                                           1543
#define  ER_TRG_CORRUPTED_FILE                                                1544
#define  ER_TRG_NO_CREATION_CTX                                               1545
#define  ER_TRG_INVALID_CREATION_CTX                                          1546
#define  ER_EVENT_INVALID_CREATION_CTX                                        1547
#define  ER_TRG_CANT_OPEN_TABLE                                               1548
#define  ER_CANT_CREATE_SROUTINE                                              1549
#define  ER_NEVER_USED                                                        1550
#define  ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT               1551
#define  ER_LOAD_DATA_INVALID_COLUMN                                          1552
#define  ER_LOG_PURGE_NO_FILE                                                 1553
#define  ER_XA_RBTIMEOUT                                                      1554
#define  ER_XA_RBDEADLOCK                                                     1555
#define  ER_NEED_REPREPARE                                                    1556
#define  ER_DELAYED_NOT_SUPPORTED                                             1557
#define  WARN_NO_MASTER_INFO                                                  1558
#define  WARN_OPTION_IGNORED                                                  1559
#define  WARN_PLUGIN_DELETE_BUILTIN                                           1560
#define  WARN_PLUGIN_BUSY                                                     1561
#define  ER_VARIABLE_IS_READONLY                                              1562
#define  ER_WARN_ENGINE_TRANSACTION_ROLLBACK                                  1563
#define  ER_SLAVE_HEARTBEAT_FAILURE                                           1564
#define  ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE                                1565
#define  ER_NDB_REPLICATION_SCHEMA_ERROR                                      1566
#define  ER_CONFLICT_FN_PARSE_ERROR                                           1567
#define  ER_EXCEPTIONS_WRITE_ERROR                                            1568
#define  ER_TOO_LONG_TABLE_COMMENT                                            1569
#define  ER_TOO_LONG_FIELD_COMMENT                                            1570
#define  ER_FUNC_INEXISTENT_NAME_COLLISION                                    1571
#define  ER_DATABASE_NAME                                                     1572
#define  ER_TABLE_NAME                                                        1573
#define  ER_PARTITION_NAME                                                    1574
#define  ER_SUBPARTITION_NAME                                                 1575
#define  ER_TEMPORARY_NAME                                                    1576
#define  ER_RENAMED_NAME                                                      1577
#define  ER_TOO_MANY_CONCURRENT_TRXS                                          1578
#define  WARN_NON_ASCII_SEPARATOR_NOT_IMPLEMENTED                             1579
#define  ER_DEBUG_SYNC_TIMEOUT                                                1580
#define  ER_DEBUG_SYNC_HIT_LIMIT                                              1581
#define  ER_DUP_SIGNAL_SET                                                    1582
#define  ER_SIGNAL_WARN                                                       1583
#define  ER_SIGNAL_NOT_FOUND                                                  1584
#define  ER_SIGNAL_EXCEPTION                                                  1585
#define  ER_RESIGNAL_WITHOUT_ACTIVE_HANDLER                                   1586
#define  ER_SIGNAL_BAD_CONDITION_TYPE                                         1587
#define  WARN_COND_ITEM_TRUNCATED                                             1588
#define  ER_COND_ITEM_TOO_LONG                                                1589
#define  ER_UNKNOWN_LOCALE                                                    1590
#define  ER_SLAVE_IGNORE_SERVER_IDS                                           1591
#define  ER_QUERY_CACHE_DISABLED                                              1592
#define  ER_SAME_NAME_PARTITION_FIELD                                         1593
#define  ER_PARTITION_COLUMN_LIST_ERROR                                       1594
#define  ER_WRONG_TYPE_COLUMN_VALUE_ERROR                                     1595
#define  ER_TOO_MANY_PARTITION_FUNC_FIELDS_ERROR                              1596
#define  ER_MAXVALUE_IN_VALUES_IN                                             1597
#define  ER_TOO_MANY_VALUES_ERROR                                             1598
#define  ER_ROW_SINGLE_PARTITION_FIELD_ERROR                                  1599
#define  ER_FIELD_TYPE_NOT_ALLOWED_AS_PARTITION_FIELD                         1600
#define  ER_PARTITION_FIELDS_TOO_LONG                                         1601
#define  ER_BINLOG_ROW_ENGINE_AND_STMT_ENGINE                                 1602
#define  ER_BINLOG_ROW_MODE_AND_STMT_ENGINE                                   1603
#define  ER_BINLOG_UNSAFE_AND_STMT_ENGINE                                     1604
#define  ER_BINLOG_ROW_INJECTION_AND_STMT_ENGINE                              1605
#define  ER_BINLOG_STMT_MODE_AND_ROW_ENGINE                                   1606
#define  ER_BINLOG_ROW_INJECTION_AND_STMT_MODE                                1607
#define  ER_BINLOG_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE                   1608
#define  ER_BINLOG_UNSAFE_LIMIT                                               1609
#define  ER_BINLOG_UNSAFE_INSERT_DELAYED                                      1610
#define  ER_BINLOG_UNSAFE_SYSTEM_TABLE                                        1611
#define  ER_BINLOG_UNSAFE_AUTOINC_COLUMNS                                     1612
#define  ER_BINLOG_UNSAFE_UDF                                                 1613
#define  ER_BINLOG_UNSAFE_SYSTEM_VARIABLE                                     1614
#define  ER_BINLOG_UNSAFE_SYSTEM_FUNCTION                                     1615
#define  ER_BINLOG_UNSAFE_NONTRANS_AFTER_TRANS                                1616
#define  ER_MESSAGE_AND_STATEMENT                                             1617
#define  ER_SLAVE_CONVERSION_FAILED                                           1618
#define  ER_SLAVE_CANT_CREATE_CONVERSION                                      1619
#define  ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_FORMAT                  1620
#define  ER_PATH_LENGTH                                                       1621
#define  ER_WARN_DEPRECATED_SYNTAX_NO_REPLACEMENT                             1622
#define  ER_WRONG_NATIVE_TABLE_STRUCTURE                                      1623
#define  ER_WRONG_PERFSCHEMA_USAGE                                            1624
#define  ER_WARN_I_S_SKIPPED_TABLE                                            1625
#define  ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_BINLOG_DIRECT                  1626
#define  ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_DIRECT                     1627
#define  ER_SPATIAL_MUST_HAVE_GEOM_COL                                        1628
#define  ER_LOCK_ABORTED                                                      1629
#define  ER_DATA_OUT_OF_RANGE                                                 1630
#define  ER_WRONG_SPVAR_TYPE_IN_LIMIT                                         1631
#define  ER_BINLOG_UNSAFE_MULTIPLE_ENGINES_AND_SELF_LOGGING_ENGINE            1632
#define  ER_BINLOG_UNSAFE_MIXED_STATEMENT                                     1633
#define  ER_INSIDE_TRANSACTION_PREVENTS_SWITCH_SQL_LOG_BIN                    1634
#define  ER_STORED_FUNCTION_PREVENTS_SWITCH_SQL_LOG_BIN                       1635
#define  ER_FAILED_READ_FROM_PAR_FILE                                         1636
#define  ER_VALUES_IS_NOT_INT_TYPE_ERROR                                      1637
#define  ER_ACCESS_DENIED_NO_PASSWORD_ERROR                                   1638
#define  ER_SET_PASSWORD_AUTH_PLUGIN                                          1639
#define  ER_GRANT_PLUGIN_USER_EXISTS                                          1640
#define  ER_TRUNCATE_ILLEGAL_FK                                               1641
#define  ER_PLUGIN_IS_PERMANENT                                               1642
#define  ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE_MIN                            1643
#define  ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE_MAX                            1644
#define  ER_STMT_CACHE_FULL                                                   1645
#define  ER_MULTI_UPDATE_KEY_CONFLICT                                         1646
#define  ER_TABLE_NEEDS_REBUILD                                               1647
#define  WARN_OPTION_BELOW_LIMIT                                              1648
#define  ER_INDEX_COLUMN_TOO_LONG                                             1649
#define  ER_ERROR_IN_TRIGGER_BODY                                             1650
#define  ER_ERROR_IN_UNKNOWN_TRIGGER_BODY                                     1651
#define  ER_INDEX_CORRUPT                                                     1652
#define  ER_UNDO_RECORD_TOO_BIG                                               1653
#define  ER_BINLOG_UNSAFE_INSERT_IGNORE_SELECT                                1654
#define  ER_BINLOG_UNSAFE_INSERT_SELECT_UPDATE                                1655
#define  ER_BINLOG_UNSAFE_REPLACE_SELECT                                      1656
#define  ER_BINLOG_UNSAFE_CREATE_IGNORE_SELECT                                1657
#define  ER_BINLOG_UNSAFE_CREATE_REPLACE_SELECT                               1658
#define  ER_BINLOG_UNSAFE_UPDATE_IGNORE                                       1659
#define  ER_PLUGIN_NO_UNINSTALL                                               1660
#define  ER_PLUGIN_NO_INSTALL                                                 1661
#define  ER_BINLOG_UNSAFE_WRITE_AUTOINC_SELECT                                1662
#define  ER_BINLOG_UNSAFE_CREATE_SELECT_AUTOINC                               1663
#define  ER_BINLOG_UNSAFE_INSERT_TWO_KEYS                                     1664
#define  ER_TABLE_IN_FK_CHECK                                                 1665
#define  ER_UNSUPPORTED_ENGINE                                                1666
#define  ER_BINLOG_UNSAFE_AUTOINC_NOT_FIRST                                   1667
#define  ER_CANNOT_LOAD_FROM_TABLE_V2                                         1668
#define  ER_MASTER_DELAY_VALUE_OUT_OF_RANGE                                   1669
#define  ER_ONLY_FD_AND_RBR_EVENTS_ALLOWED_IN_BINLOG_STATEMENT                1670
#define  ER_PARTITION_EXCHANGE_DIFFERENT_OPTION                               1671
#define  ER_PARTITION_EXCHANGE_PART_TABLE                                     1672
#define  ER_PARTITION_EXCHANGE_TEMP_TABLE                                     1673
#define  ER_PARTITION_INSTEAD_OF_SUBPARTITION                                 1674
#define  ER_UNKNOWN_PARTITION                                                 1675
#define  ER_TABLES_DIFFERENT_METADATA                                         1676
#define  ER_ROW_DOES_NOT_MATCH_PARTITION                                      1677
#define  ER_BINLOG_CACHE_SIZE_GREATER_THAN_MAX                                1678
#define  ER_WARN_INDEX_NOT_APPLICABLE                                         1679
#define  ER_PARTITION_EXCHANGE_FOREIGN_KEY                                    1680
#define  ER_NO_SUCH_KEY_VALUE                                                 1681
#define  ER_RPL_INFO_DATA_TOO_LONG                                            1682
#define  ER_BINLOG_READ_EVENT_CHECKSUM_FAILURE                                1683
#define  ER_BINLOG_STMT_CACHE_SIZE_GREATER_THAN_MAX                           1684
#define  ER_CANT_UPDATE_TABLE_IN_CREATE_TABLE_SELECT                          1685
#define  ER_PARTITION_CLAUSE_ON_NONPARTITIONED                                1686
#define  ER_ROW_DOES_NOT_MATCH_GIVEN_PARTITION_SET                            1687
#define  ER_NO_SUCH_PARTITION__UNUSED                                         1688
#define  ER_CHANGE_RPL_INFO_REPOSITORY_FAILURE                                1689
#define  ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_CREATED_TEMP_TABLE             1690
#define  ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_DROPPED_TEMP_TABLE             1691
#define  ER_MTS_FEATURE_IS_NOT_SUPPORTED                                      1692
#define  ER_MTS_UPDATED_DBS_GREATER_MAX                                       1693
#define  ER_MTS_CANT_PARALLEL                                                 1694
#define  ER_MTS_INCONSISTENT_DATA                                             1695
#define  ER_FULLTEXT_NOT_SUPPORTED_WITH_PARTITIONING                          1696
#define  ER_DA_INVALID_CONDITION_NUMBER                                       1697
#define  ER_INSECURE_PLAIN_TEXT                                               1698
#define  ER_INSECURE_CHANGE_MASTER                                            1699
#define  ER_FOREIGN_DUPLICATE_KEY_WITH_CHILD_INFO                             1700
#define  ER_FOREIGN_DUPLICATE_KEY_WITHOUT_CHILD_INFO                          1701
#define  ER_SQLTHREAD_WITH_SECURE_SLAVE                                       1702
#define  ER_TABLE_HAS_NO_FT                                                   1703
#define  ER_VARIABLE_NOT_SETTABLE_IN_SF_OR_TRIGGER                            1704
#define  ER_VARIABLE_NOT_SETTABLE_IN_TRANSACTION                              1705
#define  ER_GTID_NEXT_IS_NOT_IN_GTID_NEXT_LIST                                1706
#define  ER_CANT_CHANGE_GTID_NEXT_IN_TRANSACTION_WHEN_GTID_NEXT_LIST_IS_NULL  1707
#define  ER_SET_STATEMENT_CANNOT_INVOKE_FUNCTION                              1708
#define  ER_GTID_NEXT_CANT_BE_AUTOMATIC_IF_GTID_NEXT_LIST_IS_NON_NULL         1709
#define  ER_SKIPPING_LOGGED_TRANSACTION                                       1710
#define  ER_MALFORMED_GTID_SET_SPECIFICATION                                  1711
#define  ER_MALFORMED_GTID_SET_ENCODING                                       1712
#define  ER_MALFORMED_GTID_SPECIFICATION                                      1713
#define  ER_GNO_EXHAUSTED                                                     1714
#define  ER_BAD_SLAVE_AUTO_POSITION                                           1715
#define  ER_AUTO_POSITION_REQUIRES_GTID_MODE_ON                               1716
#define  ER_CANT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET              1717
#define  ER_GTID_MODE_2_OR_3_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON             1718
#define  ER_GTID_MODE_REQUIRES_BINLOG                                         1719
#define  ER_CANT_SET_GTID_NEXT_TO_GTID_WHEN_GTID_MODE_IS_OFF                  1720
#define  ER_CANT_SET_GTID_NEXT_TO_ANONYMOUS_WHEN_GTID_MODE_IS_ON              1721
#define  ER_CANT_SET_GTID_NEXT_LIST_TO_NON_NULL_WHEN_GTID_MODE_IS_OFF         1722
#define  ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF                            1723
#define  ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE                               1724
#define  ER_GTID_UNSAFE_CREATE_SELECT                                         1725
#define  ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION            1726
#define  ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME                      1727
#define  ER_MASTER_HAS_PURGED_REQUIRED_GTIDS                                  1728
#define  ER_CANT_SET_GTID_NEXT_WHEN_OWNING_GTID                               1729
#define  ER_UNKNOWN_EXPLAIN_FORMAT                                            1730
#define  ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION                             1731
#define  ER_TOO_LONG_TABLE_PARTITION_COMMENT                                  1732
#define  ER_SLAVE_CONFIGURATION                                               1733
#define  ER_INNODB_FT_LIMIT                                                   1734
#define  ER_INNODB_NO_FT_TEMP_TABLE                                           1735
#define  ER_INNODB_FT_WRONG_DOCID_COLUMN                                      1736
#define  ER_INNODB_FT_WRONG_DOCID_INDEX                                       1737
#define  ER_INNODB_ONLINE_LOG_TOO_BIG                                         1738
#define  ER_UNKNOWN_ALTER_ALGORITHM                                           1739
#define  ER_UNKNOWN_ALTER_LOCK                                                1740
#define  ER_MTS_CHANGE_MASTER_CANT_RUN_WITH_GAPS                              1741
#define  ER_MTS_RECOVERY_FAILURE                                              1742
#define  ER_MTS_RESET_WORKERS                                                 1743
#define  ER_COL_COUNT_DOESNT_MATCH_CORRUPTED_V2                               1744
#define  ER_SLAVE_SILENT_RETRY_TRANSACTION                                    1745
#define  ER_DISCARD_FK_CHECKS_RUNNING                                         1746
#define  ER_TABLE_SCHEMA_MISMATCH                                             1747
#define  ER_TABLE_IN_SYSTEM_TABLESPACE                                        1748
#define  ER_IO_READ_ERROR                                                     1749
#define  ER_IO_WRITE_ERROR                                                    1750
#define  ER_TABLESPACE_MISSING                                                1751
#define  ER_TABLESPACE_EXISTS                                                 1752
#define  ER_TABLESPACE_DISCARDED                                              1753
#define  ER_INTERNAL_ERROR                                                    1754
#define  ER_INNODB_IMPORT_ERROR                                               1755
#define  ER_INNODB_INDEX_CORRUPT                                              1756
#define  ER_INVALID_YEAR_COLUMN_LENGTH                                        1757
#define  ER_MUST_CHANGE_PASSWORD                                              1758
#define  ER_FK_NO_INDEX_CHILD                                                 1759
#define  ER_FK_NO_INDEX_PARENT                                                1760
#define  ER_FK_FAIL_ADD_SYSTEM                                                1761
#define  ER_FK_CANNOT_OPEN_PARENT                                             1762
#define  ER_FK_INCORRECT_OPTION                                               1763
#define  ER_FK_DUP_NAME                                                       1764
#define  ER_PASSWORD_FORMAT                                                   1765
#define  ER_FK_COLUMN_CANNOT_DROP                                             1766
#define  ER_FK_COLUMN_CANNOT_DROP_CHILD                                       1767
#define  ER_FK_COLUMN_NOT_NULL                                                1768
#define  ER_FK_COLUMN_CANNOT_CHANGE                                           1769
#define  ER_FK_COLUMN_CANNOT_CHANGE_CHILD                                     1770
#define  ER_FK_CANNOT_DELETE_PARENT                                           1771
#define  ER_MALFORMED_PACKET                                                  1772
#define  ER_READ_ONLY_MODE                                                    1773
#define  ER_GTID_NEXT_TYPE_UNDEFINED_GROUP                                    1774
#define  ER_VARIABLE_NOT_SETTABLE_IN_SP                                       1775
#define  ER_CANT_SET_GTID_PURGED_WHEN_GTID_MODE_IS_OFF                        1776
#define  ER_CANT_SET_GTID_PURGED_WHEN_GTID_EXECUTED_IS_NOT_EMPTY              1777
#define  ER_CANT_SET_GTID_PURGED_WHEN_OWNED_GTIDS_IS_NOT_EMPTY                1778
#define  ER_GTID_PURGED_WAS_CHANGED                                           1779
#define  ER_GTID_EXECUTED_WAS_CHANGED                                         1780
#define  ER_BINLOG_STMT_MODE_AND_NO_REPL_TABLES                               1781
#define  ER_ALTER_OPERATION_NOT_SUPPORTED                                     1782
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON                              1783
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COPY                         1784
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_PARTITION                    1785
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_RENAME                    1786
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COLUMN_TYPE                  1787
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_CHECK                     1788
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_IGNORE                       1789
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOPK                         1790
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_AUTOINC                      1791
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_HIDDEN_FTS                   1792
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS                   1793
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FTS                          1794
#define  ER_SQL_SLAVE_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE                  1795
#define  ER_DUP_UNKNOWN_IN_INDEX                                              1796
#define  ER_IDENT_CAUSES_TOO_LONG_PATH                                        1797
#define  ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOT_NULL                     1798
#define  ER_NISAMCHK                                                          1799
#define  ER_NOT_SUPPORTED_YET                                                 1800
#define  ER_SQL_NO_SOURCE                                                     1801
#define  ER_SQL_NO_OP_TYPE                                                    1802
#define  ER_SQL_INVALID_OP_TYPE                                               1803
#define  ER_PARSE_ERROR                                                       1804
#define  ER_SYNTAX_ERROR                                                      1805
#define  ER_REMOTE_EXE_ERROR                                                  1806
#define  ER_SHUTDOWN_COMPLETE                                                 1807
#define  ER_WITH_INSERT_FIELD                                                 1808
#define  ER_WITH_INSERT_VALUES                                                1809
#define  ER_WRONG_VALUE_COUNT_ON_ROW                                          1810
#define  ER_BAD_FIELD_ERROR                                                   1811
#define  ER_FIELD_SPECIFIED_TWICE                                             1812
#define  ER_BAD_NULL_ERROR                                                    1813
#define  ER_NO_WHERE_CONDITION                                                1814
#define  ER_NORMAL_SHUTDOWN                                                   1815
#define  ER_FORCING_CLOSE                                                     1816
#define  ER_CON_COUNT_ERROR                                                   1817
#define  ER_INVALID_COMMAND                                                   1818
#define  ER_SQL_INVALID_SOURCE                                                1819
#define  ER_WRONG_DB_NAME                                                     1820
#define  EXIT_UNKNOWN_VARIABLE                                                1821
#define  EXIT_UNKNOWN_OPTION                                                  1822
#define  ER_NO_DB_ERROR                                                       1823
#define  ER_WITH_LIMIT_CONDITION                                              1824
#define  ER_WITH_ORDERBY_CONDITION                                            1825
#define  ER_SELECT_ONLY_STAR                                                  1826
#define  ER_ORDERY_BY_RAND                                                    1827
#define  ER_ID_IS_UPER                                                        1828
#define  ER_UNKNOWN_COLLATION                                                 1829
#define  ER_INVALID_DATA_TYPE                                                 1830
#define  ER_NOT_ALLOWED_NULLABLE                                              1831
#define  ER_DUP_FIELDNAME                                                     1832
#define  ER_WRONG_COLUMN_NAME                                                 1833
#define  ER_WRONG_AUTO_KEY                                                    1834
#define  ER_TABLE_CANT_HANDLE_AUTO_INCREMENT                                  1835
#define  ER_FOREIGN_KEY                                                       1836
#define  ER_TOO_MANY_KEY_PARTS                                                1837
#define  ER_TOO_LONG_IDENT                                                    1838
#define  ER_UDPATE_TOO_MUCH_ROWS                                              1839
#define  ER_WRONG_NAME_FOR_INDEX                                              1840
#define  ER_TOO_MANY_KEYS                                                     1841
#define  ER_NOT_SUPPORTED_KEY_TYPE                                            1842
#define  ER_WRONG_SUB_KEY                                                     1843
#define  ER_WRONG_KEY_COLUMN                                                  1844
#define  ER_TOO_LONG_KEY                                                      1845
#define  ER_MULTIPLE_PRI_KEY                                                  1846
#define  ER_DUP_KEYNAME                                                       1847
#define  ER_TOO_LONG_INDEX_COMMENT                                            1848
#define  ER_DUP_INDEX                                                         1849
#define  ER_TEMP_TABLE_TMP_PREFIX                                             1850
#define  ER_TABLE_MUST_INNODB                                                 1851
#define  ER_TABLE_CHARSET_MUST_UTF8                                           1852
#define  ER_TABLE_MUST_HAVE_COMMENT                                           1853
#define  ER_COLUMN_HAVE_NO_COMMENT                                            1854
#define  ER_TABLE_MUST_HAVE_PK                                                1855
#define  ER_PARTITION_NOT_ALLOWED                                             1856
#define  ER_USE_ENUM                                                          1857
#define  ER_USE_TEXT_OR_BLOB                                                  1858
#define  ER_COLUMN_EXISTED                                                    1859
#define  ER_COLUMN_NOT_EXISTED                                                1860
#define  ER_CANT_DROP_FIELD_OR_KEY                                            1861
#define  ER_INVALID_DEFAULT                                                   1862
#define  ER_USERNAME                                                          1863
#define  ER_HOSTNAME                                                          1864
#define  ER_NOT_VALID_PASSWORD                                                1865
#define  ER_WRONG_STRING_LENGTH                                               1866
#define  ER_BLOB_USED_AS_KEY                                                  1867
#define  ER_TOO_LONG_BAKDB_NAME                                               1868
#define  ER_INVALID_BACKUP_HOST_INFO                                          1869
#define  ER_NET_READ_ERROR                                                    1870
#define  ER_BINLOG_CORRUPTED                                                  1871
#define  ER_NETWORK_READ_EVENT_CHECKSUM_FAILURE                               1872
#define  ER_SLAVE_RELAY_LOG_WRITE_FAILURE                                     1873
#define  ER_INCORRECT_GLOBAL_LOCAL_VAR                                        1874
#define  ER_START_AS_BEGIN                                                    1875
#define  ER_OUTOFMEMORY                                                       1876
#define  ER_HAVE_BEGIN                                                        1877
#define  ER_NET_READ_INTERRUPTED                                              1878
#define  ER_BINLOG_FORMAT_STATEMENT                                           1879
#define  EXIT_NO_ARGUMENT_ALLOWED                                             1880
#define  EXIT_ARGUMENT_REQUIRED                                               1881
#define  EXIT_AMBIGUOUS_OPTION                                                1882
#define  ER_ERROR_EXIST_BEFORE                                                1883
#define  ER_UNKNOWN_SYSTEM_VARIABLE                                           1884
#define  ER_UNKNOWN_CHARACTER_SET                                             1885
#define  ER_END_WITH_COMMIT                                                   1886
#define  ER_DB_NOT_EXISTED_ERROR                                              1887
#define  ER_TABLE_EXISTS_ERROR                                                1888
#define  ER_INDEX_NAME_IDX_PREFIX                                             1889
#define  ER_INDEX_NAME_UNIQ_PREFIX                                            1890
#define  ER_AUTOINC_UNSIGNED                                                  1891
#define  ER_VARCHAR_TO_TEXT_LEN                                               1892
#define  ER_CHAR_TO_VARCHAR_LEN                                               1893
#define  ER_KEY_COLUMN_DOES_NOT_EXITS                                         1894
#define  ER_INC_INIT_ERR                                                      1895
#define  ER_WRONG_ARGUMENTS                                                   1896
#define  ER_SET_DATA_TYPE_INT_BIGINT                                          1897
#define  ER_TIMESTAMP_DEFAULT                                                 1898
#define  ER_CHARSET_ON_COLUMN                                                 1899
#define  ER_AUTO_INCR_ID_WARNING                                              1900
#define  ER_ALTER_TABLE_ONCE                                                  1901
#define  ER_BLOB_CANT_HAVE_DEFAULT                                            1902
#define  ER_END_WITH_SEMICOLON                                                1903
#define  ER_NON_UNIQ_ERROR                                                    1904
#define  ER_TABLE_NOT_EXISTED_ERROR                                           1905
#define  ER_UNKNOWN_TABLE                                                     1906
#define  ER_INVALID_GROUP_FUNC_USE                                            1907
#define  ER_INDEX_USE_ALTER_TABLE                                             1908
#define  ER_WITH_DEFAULT_ADD_COLUMN                                           1909
#define  ER_TRUNCATED_WRONG_VALUE                                             1910
#define  ER_TEXT_NOT_NULLABLE_ERROR                                           1911
#define  ER_WRONG_VALUE_FOR_VAR                                               1912
#define  ER_TOO_MUCH_AUTO_TIMESTAMP_COLS                                      1913
#define  ER_INVALID_ON_UPDATE                                                 1914
#define  ER_DDL_DML_COEXIST                                                   1915
#define  ER_SLAVE_CORRUPT_EVENT                                               1916
#define  ER_NAMES_MUST_UTF8                                                   1917
#define  ER_COLLATION_CHARSET_MISMATCH                                        1918
#define  ER_NOT_SUPPORTED_ALTER_OPTION                                        1919
#define  ER_CONFLICTING_DECLARATIONS                                          1920
#define  ER_IDENT_USE_KEYWORD                                                 1921
#define  ER_VIEW_SELECT_CLAUSE                                                1922
#define  ER_OSC_KILL_FAILED                                                   1923
#define  ER_NET_PACKETS_OUT_OF_ORDER                                          1924
#define  ER_NOT_SUPPORTED_ITEM_TYPE                                           1925
#define  ER_INVALID_IDENT                                                     1926
#define  ER_DB_EXISTS                                                         1927
#define  ER_SUBSELECT_IN_DML                                                  1928
#define  ER_ADD_INSTANCE_ERROR                                                1929
#define  ER_INSTANCE_EXISTED                                                  1930
#define  ER_INVALID_DATACENTER_INFO                                           1931
#define  ER_TRANSFER_INTERRUPT                                                1932
#define  ER_TRANSFER_RUNNING                                                  1933
#define  ER_TRANSFER_NONRUNNING                                               1934
#define  ER_TRANSFER_INTERRUPT_DC                                             1935
#define  ER_TRANSFER_NOT_EXISTED                                              1936
#define  ER_MASTER_NODE_FIRST                                                 1937
#define  ER_TASK_ALREADY_EXISTED                                              1938
#define  ER_INVALID_TRANSFER_INFO                                             1939
#define  ER_DATACENTER_EXISTED                                                1940
#define  ER_REMOVED_SPACES                                                    1941
#define  ER_NET_ERROR_ON_WRITE                                                1942
#define  ER_DERIVED_MUST_HAVE_ALIAS                                           1943
#define  ER_SET_OPTIONS_ERROR                                                 1944
#define  ER_DIFF_TYPE_COMPARE_FIELD                                           1945
#define  ER_DIFF_CHARSET_COMPARE_FIELD                                        1946
#define  ER_LIKE_COMP_PREFIX_PERCENT                                          1947
#define  ER_FUNC_EXISTED_ON_FIELD                                             1948
#define  ER_ADD_INDEX                                                         1949
#define  ER_CONVERT_DATA_TYPE                                                 1950
#define  ER_INDEX_USED_TRUNCATE                                               1951
#define  ER_UNKNOWN_COLLECTOR_RULE                                            1952
#define  ER_UNKNOWN_COLLECTOR_THREAD                                          1953
#define  ER_ERROR_LAST                                                        1954
